actividades/urls.py
from django.urls import path, include
from .views import ActividadesHome
from . import views
from django.contrib import admin
app_name= "actividades"
urlpatterns = [
    path('', ActividadesHome.as_view() , name="home"),
    path('admin/', admin.site.urls , name="admin"),
    path('generador/', views.ActividadesGenerador.as_view() , name="generador"),
    path('detalle/<int:pk>/', views.ActividadesDetalle.as_view(), name='detalle' ),
    path('crear/', views.ActividadesCrear.as_view(), name="crear"),
    path('editar/<int:pk>/', views.ActividadesEditar.as_view(), name="editar"),
    path('eliminar/<int:pk>/', views.ActividadesEliminar.as_view(), name="eliminar"),
]

blog/urls.py
from django.urls import path
from . import views
app_name = "blog"
urlpatterns = [
    path('', views.BlogHome.as_view(), name='home' ),
    path('generator/', views.BlogGenerator.as_view(), name='generator'),
    path('detail/<int:pk>', views.BlogDetail.as_view(), name='detail'),
    path('crear', views.BlogCreate.as_view(), name='crear'),
    path('update/<int:pk>', views.BlogUpdate.as_view(), name='update'),
]

vistas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('actividades.urls')),
    path('blog/', include('blog.urls')),
]

actividades/models.py
from django.db import models
from django.utils import timesince
class EtiquetaImportancia(models.Model):
    titulo = models.CharField(max_length=32, null=False, verbose_name="título")
    fecha_creacion = models.DateTimeField(auto_now_add=True, verbose_name="fecha creación")

    def __str__(self):
        return self.titulo
    class Meta: 
        verbose_name_plural="Etiquetas de importancia"

class EtiquetaEstado(models.Model):
    titulo = models.CharField(max_length=32, null=False, verbose_name="título")
    fecha_creacion = models.DateTimeField(auto_now_add=True, verbose_name="fecha creación")
    
    def __str__(self):
        return self.titulo
    class Meta: 
        verbose_name_plural="Etiquetas de estado"

class Actividad(models.Model):
    titulo = models.CharField(max_length=256, null=False, verbose_name="título")
    descripcion = models.TextField(verbose_name="descripción")
    fecha_inicio = models.DateField()
    fecha_limite = models.DateField(verbose_name="fecha límite")
    importancia = models.ForeignKey(EtiquetaImportancia, on_delete=models.CASCADE)
    estado = models.ForeignKey(EtiquetaEstado, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(auto_now_add=True, verbose_name="fecha creación")
    fecha_actualizacion = models.DateTimeField(auto_now=True, verbose_name="fecha actualización")

    def __str__(self):
        return self.titulo
    @property
    def time_since(self):
        return timesince.timesince(self.fecha_creacion)
    class Meta: 
        verbose_name_plural="Actividades"
        ordering = ['fecha_creacion']

blog/models.py
from django.db import models

class EntradaBlog(models.Model):
    titulo = models.CharField(max_length=128, verbose_name="Título")
    contenido = models.TextField(verbose_name="Contenido")
    fecha_creacion = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    fecha_actualizacion = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización")
    class Meta():
        verbose_name_plural = "Blogs"
        verbose_name = "Blog"
        ordering = ['fecha_creacion']
    def __str__(self): 
        return self.titulo

actividades/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Actividad, EtiquetaImportancia, EtiquetaEstado
from django.views import View
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
import lorem
import datetime
import random
class ActividadesHome(ListView):   
    model = Actividad 
    #Nombre de la plantilla que django busca por defecto : actividad_list
    # Para cambiar el nombre de la plantilla se usa template_name = 
    template_name = 'actividades/home.html'
    #Nombre de los elementos del contexto: actividad_list
    # context_object_name= cambia el nombre de los elementos del contexto
    paginate_by = 3
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        param_get = '&'.join([f'{p}={k}' for p,k in self.request.GET.items() if p != 'page'])
        context["param_get"] = param_get
        return context
    def get_queryset(self):
        importancia_pk = self.request.GET.get('ipk', None)
        estado_pk = self.request.GET.get('epk', None)
        objetos = Actividad.objects.all()
        if importancia_pk: 
            objetos = objetos.filter(importancia=importancia_pk)
        if estado_pk: 
            objetos = objetos.filter(estado=estado_pk)
        return objetos
class ActividadesGenerador(View):
    def get(self, request):
        return render(request, template_name='actividades/generador.html')
    
    def post(self, request):
        # Número de actividades indicadas en el formulario
        cantidad = int(request.POST.get('cantidad', 0))
        # Fecha mínima de inicio de las actividades
        fecha_base = datetime.date(year=2022, month=1, day=1)
        # Lista de etiquetas existentes
        et_importancia = EtiquetaImportancia.objects.all()
        et_estado = EtiquetaEstado.objects.all()
        for _ in range(cantidad):
            actividad = Actividad()
            actividad.titulo = lorem.sentence()
            actividad.descripcion = lorem.paragraph()
            actividad.fecha_inicio = fecha_base + datetime.timedelta(days=random.randint(0, 100))
            actividad.fecha_limite = actividad.fecha_inicio + datetime.timedelta(days=random.randint(30, 90))
            actividad.importancia = et_importancia[random.randint(0, len(et_importancia) - 1)]
            actividad.estado = et_estado[random.randint(0, len(et_estado) - 1)]
            actividad.save()
        return redirect('actividades:home')

class ActividadesDetalle(DetailView):
    model = Actividad
    template_name = 'actividades/detalle.html'
class ActividadesCrear(CreateView):
    extra_context = {'importancias':EtiquetaImportancia.objects.all(),
        'estados':EtiquetaEstado.objects.all(),
        'accion': 'crear'}
    template_name = 'actividades/crear.html'
    model = Actividad
    fields = ['titulo', 'descripcion', 'fecha_inicio', 'fecha_limite', 'importancia', 'estado']
    success_url = reverse_lazy('actividades:home')
class ActividadesEditar(UpdateView):
    extra_context = {'importancias':EtiquetaImportancia.objects.all(),
        'estados':EtiquetaEstado.objects.all(),
        'accion': 'editar'}
    template_name = 'actividades/crear.html'
    model = Actividad
    fields = ['titulo', 'descripcion', 'fecha_inicio', 'fecha_limite', 'importancia', 'estado']
    def get_success_url(self):
        return reverse('actividades:detalle', args=(self.kwargs['pk'],))
class ActividadesEliminar(DeleteView):
    model = Actividad
    template_name = 'actividades/detalle.html'
    success_url = reverse_lazy('actividades:home')
    extra_context = {'confirmar_eliminar' : True}

blog/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from . import models
from django.views import View
from django.shortcuts import render, redirect
import lorem
from django.urls import reverse_lazy
class BlogHome(ListView): 
    model = models.EntradaBlog
    template_name= 'blog/blog_home.html'
    context_object_name = 'blogs'
    paginate_by = 5
class BlogGenerator(CreateView):
    def get(self, request):
        return render(request, template_name=('blog/blog_generator.html'))
    def post(self, request): 
        cantidad = int(request.POST.get('cantidad', 0))
        for _ in range(cantidad):
            models.EntradaBlog.objects.create(
                titulo = lorem.sentence(), 
                contenido = lorem.paragraph()
            ).save()
        return redirect('blog:home')
class BlogDetail(DetailView):
    model = models.EntradaBlog
    template_name = 'blog/detail.html'
class BlogCreate(CreateView):
    template_name = 'blog/crear.html'
    model = models.EntradaBlog
    fields = ['titulo', 'contenido']
    success_url = reverse_lazy('blog:home')
class BlogUpdate(UpdateView):
    template_name = 'blog/update.html'
    model = models.EntradaBlog
    fields = ['titulo', 'contenido']
    success_url = reverse_lazy('blog:home')

actividades/templates/actividades/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Actividades</title>
</head>
<body>
    {% url 'actividades:home' as url_home %}
    {% url 'actividades:generador' as url_generador %}
    {% url 'blog:blog_home' as url_blog %}
    {% url 'actividades:crear' as url_crear %}
    <div class="container-fluid bg-primary p-5">
        <h1 class="display-5 text-white">Proyecto módulo 6</h1>
    </div>

    <div class="container-fluid px-0 sticky-{}">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark py-2">
            <div class="container-fluid">
                <!-- Logo o marca -->
                <a class="navbar-brand" href="#">
                    <span><i class="fa-brands fa-html5"></i></span>
                </a>
                
                <!-- Botón para mostrar y ocultar el menú (solo visible cuando está colapsado)
                El target tiene que concidir con el ID del contenido del navbar -->
                <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#contenido_navbar" aria-expanded="false">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="contenido_navbar">
                    <!-- .me-auto es para que todo lo que esté fuera de la lista
                    se pegue al lado derecho -->
                    <ul class="navbar-nav me-auto mb-0 pt-3 pt-sm-0">
                        <div class="dropdown mx-2">
                            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Actividades
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'actividades:home' %}">Lista de actividades</a></li>
                              <li><a class="dropdown-item" href="{% url 'actividades:generador' %}">Generador de actividades</a></li>
                              <li><a class="dropdown-item" href="{% url 'actividades:crear' %}">Crear actividad</a></li>
                            </ul>
                        </div>
                        <div class="dropdown">
                            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Blog
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="{% url 'blog:home' %}">Lista de blogs</a></li>
                              <li><a class="dropdown-item" href="{% url 'blog:generator' %}">Generador de blogs</a></li>
                              <li><a class="dropdown-item" href="{% url 'blog:crear' %}">Crear blog</a></li>
                            </ul>
                        </div>
                    </ul>
                    <div class="d-flex pt-3 pt-sm-0 me-2 text-light flex-column flex-sm-row gap-3">
                        <a class="text-decoration-none text-light me-3" href="{% url 'admin:index' %}">Administrador</a>
                        <span class="d-none d-sm-inline"><i class="fa-solid fa-user"></i></span>
                    </div>
                    
                </div>
            </div>
        </nav>
    </div>

    {% block contenido %}{% endblock %}

</body>
</html>

actividades/templates/actividades/crear.html
{% extends 'actividades/base.html' %}

{% block contenido %}
<div class="container my-5">
    <h1 class="display-6">{{accion|title}} actividad</h1>
</div>
<div class="container">
    <form class="bg-light border my-5 p-3 rounded shadow" method="post">
        {% csrf_token %}
        <div class="my-3">
            <div class="form-floating my-3">
                <input type="text" class="form-control" id="et_titulo" placeholder="x" name="titulo" value="{{actividad.titulo}}" required>
                <label for="et_titulo">Título</label>
            </div>

            <div class="form-floating my-3">
                <textarea class="form-control" placeholder="x" id="et_descripcion" style="height:100px" name="descripcion" required>{{actividad.descripcion}}</textarea>
                <label for="et_descripcion">Descripción</label>
            </div>
            <div class="form-floating my-3">
                <input type="date" class="form-control" id="et_fecha_ini" placeholder="x" name="fecha_inicio" value="{{actividad.fecha_inicio|date:'Y-m-d'}}">
                <label for="et_fecha_ini">Fecha de inicio</label>
            </div>

            <div class="form-floating my-3">
                <input type="date" class="form-control" id="et_fecha_lim" placeholder="x" name="fecha_limite" value="{{actividad.fecha_limite|date:'Y-m-d'}}">
                <label for="et_fecha_lim">Fecha límite</label>
            </div>
            <div class="my-3">
                <label for="et_importancia">Importancia</label>
                <select class="form-select"  id="et_importancia" name="importancia">
                    {% for importancia in importancias %}
                    <option value="{{importancia.id}}" {%  if actividad.importancia == importancia %}selected{% endif %}>{{importancia}}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="my-3">
                <label for="et_estado">Estado</label>
                <select class="form-select"  id="et_estado" name="estado">
                    {% for estado in estados %}
                    <option value="{{estado.id}}" {%  if actividad.estado == estado %}selected{% endif %}>{{estado}}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
    </form>
</div>

{% endblock %}

actividades/templates/actividades/detalle.html
{% extends 'actividades/base.html' %}

{% block contenido %}
<div class="container my-5">
    <h1 class="display-6">Detalle de actividad</h1>
</div>

<div class="container">
    <p class="lead"><strong>Título: </strong>{{actividad.titulo}}</p>
    <p class="lead"><strong>Descripción: </strong>{{actividad.descripcion}}</p>
    <p class="lead"><strong>Importancia: </strong>{{actividad.importancia}}</p>
    <p class="lead"><strong>Estado: </strong>{{actividad.estado}}</p>
    <p class="lead"><strong>Fecha límite: </strong>{{actividad.fecha_limite}}</p>
    <a class="btn btn-primary" href="{% url 'actividades:editar' actividad.id %}">Editar</a>
    <a class="btn btn-danger" href="{% url 'actividades:eliminar' actividad.id %}">Eliminar</a>
    {% if confirmar_eliminar %}
    <form method="POST" class="my-3">
        {% csrf_token %}
        <p class="lead">¿Seguro que deseas eliminar?</p>
        <button type="submit" class="btn btn-danger">Sí</button>
        <a href="{% url 'actividades:detalle' actividad.id %}" class="btn btn-secondary mx-3">No</a>
    </form>
    {% endif %}
</div>

{% endblock %}

actividades/templates/actividades/eliminar.html
{% extends 'actividades/base.html' %}

{% block contenido %}
<div class="container my-5">
    <h1>Detalle entrada de blog </h1>
    <form method="POST">
        {% csrf_token %}
        <p class="lead">¿Seguro que deseas eliminar?</p>
        <button type="submit" class="btn btn-danger">Sí</button>
        <button type="button" class="btn btn-secondary mx-3">No</button>
    </form>
</div>


{% endblock %}

actividades/templates/actividades/generador.html
{% extends 'actividades/base.html' %}

{% block contenido %}
<div class="container my-5">
    <h1 class="display-6">Generador de actividades</h1>
</div>
<div class="container">
    <!-- Como queremos que el formulario se envíe a la misma ruta, no nocesitamos el atributo action -->
    <form class="bg-light border mt-3 p-3 rounded shadow" method="post">
        <!-- Entradas agrupadas: .input-group .input-group-text -->
        {% csrf_token %}
        <div class="my-3">
            <div class="input-group my-1">
                <span class="input-group-text">Generar</span>
                <input type="text" class="form-control" name="cantidad" placeholder="" value="20">
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Generar</button>
    </form>
</div>
    

    
{% endblock %}

actividades/templates/actividades/home.html
{% extends 'actividades/base.html' %}

{% block contenido %}
<div class="container my-5">
    <h1 class="display-6">Lista de actividades</h1>
</div>

<div class="container my-5 d-flex flex-column justify-content-end gap-3">
    {% for actividad in actividad_list %}
    <div class="p-3 border rounded-3 shadow-sm">
        <div>
            <a href="{% url 'actividades:detalle' actividad.id%}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{actividad.titulo}}</h5>
                    <small>{{actividad.time_since}}</small>
                </div>
                <p class="mb-1">{{actividad.descripcion|slice:100}}...</p>
            </a>
            <a href="{% url 'actividades:home' %}?ipk={{actividad.importancia.id}}"><small class="badge bg-secondary rounded-pill">{{actividad.importancia}}</small></a>
            <a href="{% url 'actividades:home' %}?epk={{actividad.estado.id}}"><small class="badge bg-secondary rounded-pill">{{actividad.estado}}</small></a>
        </div>
    </div>
    {% endfor %}
</div>
<!-- Paginacion -->
<!-- <ul class="pagination pagination-lg justify-content-center my-5">
    <li class="page-item">
        {% if page_obj.has_previous %}
        <a class="page-link" href="?{{param_get}}&page={{page_obj.previous_page_number}}">Anterior</a>
        {% else %}
        <a class="page-link disabled" href="">Anterior</a>
        {% endif %}
    </li>

    <li class="page-item active">
        <a class="page-link" href="{{param_get}}&page={{page_obj.number}}">{{page_obj.number}} de {{page_obj.paginator.num_pages}}</a>
    </li>

    <li class="page-item">
        {% if page_obj.has_next %}
        <a class="page-link" href="?{{param_get}}&page={{page_obj.next_page_number}}">Siguiente</a>
        {% else %}
        <a class="page-link disabled" href="">Siguiente</a>
        {% endif %}
    </li>
</ul> -->
<!-- Paginacion -->
<div class="container my-5">
    <ul class="pagination pagination-lg justify-content-center my-5">
        <li class="page-item {% if not page_obj.has_previous %}active{% endif %}">
            <a class="page-link" href="?{{param_get}}&page=1">1</a>
        </li>

        {% if page_obj.paginator.num_pages >= 6 and page_obj.number >= 4 %}
        <li class="page-item disabled">
            <a class="page-link px-1" href="">{{page_obj.paginator.ELLIPSIS}}</a>
        </li>
        {% endif %}

        {% if page_obj.paginator.num_pages >= 3 %}
        <li class="page-item">
            {% if page_obj.number <= 3 or page_obj.paginator.num_pages < 5 %}
                <a class="page-link {% if page_obj.number == 2 %}active{% endif %}" href="?{{param_get}}&page=2">2</a>
            {% elif page_obj.number >= page_obj.paginator.num_pages|add:-2 %}
                {% with pag_num=page_obj.paginator.num_pages|add:-3 %}
                <a class="page-link {% if page_obj.number == pag_num %}active{% endif %}" href="?{{param_get}}&page={{pag_num}}">{{pag_num}}</a>
                {% endwith %}
            {% else %}
                {% with pag_num=page_obj.previous_page_number %}
                <a class="page-link {% if page_obj.number == pag_num %}active{% endif %}" href="?{{param_get}}&page={{pag_num}}">{{pag_num}}</a>
                {% endwith %}
            {% endif %}
        </li>
        {% endif %}

        {% if page_obj.paginator.num_pages >= 4 %}
        <li class="page-item">
            {% if page_obj.number <= 3 or page_obj.paginator.num_pages < 5 %}
                <a class="page-link {% if page_obj.number == 3 %}active{% endif %}" href="?{{param_get}}&page=3">3</a>
            {% elif page_obj.number >= page_obj.paginator.num_pages|add:-2 %}
                {% with pag_num=page_obj.paginator.num_pages|add:-2 %}
                <a class="page-link {% if page_obj.number == pag_num %}active{% endif %}" href="?{{param_get}}&page={{pag_num}}">{{pag_num}}</a>
                {% endwith %}
            {% else %}
                {% with pag_num=page_obj.number %}
                <a class="page-link {% if page_obj.number == pag_num %}active{% endif %}" href="?{{param_get}}&page={{pag_num}}">{{pag_num}}</a>
                {% endwith %}
            {% endif %}
        </li>
        {% endif %}

        {% if page_obj.paginator.num_pages >= 5 %}
        <li class="page-item">
            {% if page_obj.number <= 3 %}
                <a class="page-link {% if page_obj.number == 4 %}active{% endif %}" href="?{{param_get}}&page=4">4</a>
            {% elif page_obj.number <= page_obj.paginator.num_pages|add:-2 %}
                {% with pag_num=page_obj.next_page_number %}
                <a class="page-link {% if page_obj.number == pag_num %}active{% endif %}" href="?{{param_get}}&page={{pag_num}}">{{pag_num}}</a>
                {% endwith %}
            {% else %}
                {% with pag_num=page_obj.paginator.num_pages|add:-1 %}
                <a class="page-link {% if page_obj.number == pag_num %}active{% endif %}" href="?{{param_get}}&page={{pag_num}}">{{pag_num}}</a>
                {% endwith %}
            {% endif %}
        </li>
        {% endif %}

        {% if page_obj.paginator.num_pages >= 6 and page_obj.number <= page_obj.paginator.num_pages|add:-3 %}
        <li class="page-item disabled">
            <a class="page-link px-1" href="">{{page_obj.paginator.ELLIPSIS}}</a>
        </li>
        {% endif %}

        {% if page_obj.paginator.num_pages >= 2 %}
        <li class="page-item {% if not page_obj.has_next %}active{% endif %}">
            <a class="page-link" href="?{{param_get}}&page={{page_obj.paginator.num_pages}}">{{page_obj.paginator.num_pages}}</a>
        </li>
        {% endif %}
    </ul>
</div>
{% endblock %}

blog/templates/blog/blog_generator.html
{% extends 'actividades/base.html' %}

{% block contenido %}
<div class="container my-5">
    <h1 class="display-6">Generador de blogs</h1>
</div>
<div class="container">
    <!-- Como queremos que el formulario se envíe a la misma ruta, no nocesitamos el atributo action -->
    <form class="bg-light border mt-3 p-3 rounded shadow" method="post">
        <!-- Entradas agrupadas: .input-group .input-group-text -->
        {% csrf_token %}
        <div class="my-3">
            <div class="input-group my-1">
                <span class="input-group-text">Generar</span>
                <input type="text" class="form-control" name="cantidad" placeholder="" value="20">
            </div>
        </div>
        <button type="submit" class="btn btn-primary" value="Save">Generar</button>
    </form>
</div>
    

    
{% endblock %}

blog/templates/blog/blog_home.html
{% extends 'actividades/base.html' %}
{% block contenido %}
<div class="container my-5">
    <h1 class="display-6">Entradas de blog</h1>
</div>
<div class="container my-5 d-flex flex-column justify-content-end gap-3">
    {% for blog in blogs %}
    <div class="p-3 border rounded-3 shadow-sm">
        <div>
            <a href="{% url 'blog:detail' blog.id %} " class="list-group-item list-group-item-action">
                <div class="w-100">
                    <h3 class="mb-1">{{blog.titulo}}</h3>
                    <p>{{blog.contenido}}</p>
                    <a class="btn btn-primary" href="{% url 'blog:update' blog.id %}">Actualizar</a>
                </div>
            </a>
        </div>
    </div>
    {% endfor %}
</div>
<ul class="pagination pagination-lg justify-content-center my-5">
    <li class="page-item">
        {% if page_obj.has_previous %}
        <a class="page-link" href="?{{param_get}}&page={{page_obj.previous_page_number}}">Anterior</a>
        {% else %}
        <a class="page-link disabled" href="">Anterior</a>
        {% endif %}
    </li>

    <li class="page-item active">
        <a class="page-link" href="{{param_get}}&page={{page_obj.number}}">{{page_obj.number}} de {{page_obj.paginator.num_pages}}</a>
    </li>

    <li class="page-item">
        {% if page_obj.has_next %}
        <a class="page-link" href="?{{param_get}}&page={{page_obj.next_page_number}}">Siguiente</a>
        {% else %}
        <a class="page-link disabled" href="">Siguiente</a>
        {% endif %}
    </li>
</ul>
{% endblock %}
    
    
    

blog/templates/blog/crear.html
{% extends 'actividades/base.html' %}

{% block contenido %}
<div class="container my-5">
    <h1 class="display-6">Crear blog</h1>
</div>
<div class="container">
    <form class="bg-light border my-5 p-3 rounded shadow" method="post">
        {% csrf_token %}
        <div class="my-3">
            <div class="form-floating my-3">
                <input type="text" class="form-control" id="et_titulo" placeholder="x" name="titulo" value="" required>
                <label for="et_titulo">Título</label>
            </div>

            <div class="form-floating my-3">
                <textarea class="form-control" placeholder="x" id="et_descripcion" style="height:100px" name="contenido" required></textarea>
                <label for="et_descripcion">Contenido</label>
            </div>
            
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
    </form>
</div>

{% endblock %}

blog/templates/blog/detail.html
{% extends 'actividades/base.html'%}
{% block contenido %}

<div class="container p-2 mt-3">
    <h1>Detalle entrada de blog </h1>
    <p><strong>Título: </strong>{{entradablog.titulo}}</p>
    <p><strong>Contenido: </strong>{{entradablog.contenido}}</p>
    <p><strong>Fecha de creación: </strong>{{entradablog.fecha_creacion}}</p>
    <p><strong>Fecha de actualización: </strong>{{entradablog.fecha_actualizacion}}</p>
    <a class="btn btn-primary" href="{% url 'blog:update' entradablog.id %}">Actualizar</a>
</div>
{% endblock %}

blog/templates/blog/eliminar.html
{% extends 'actividades/base.html'%}
{% block contenido %}

<div class="container p-2 mt-3">
    <h1>Detalle entrada de blog </h1>
    <form method="POST">
        {% csrf_token %}
        <p class="lead d-inline">¿Seguro que deseas eliminar?</p>
        <button type="submit" class="btn btn-danger">Sí</button>
    </form>
</div>
{% endblock %}

blog/templates/blog/update.html
{% extends 'actividades/base.html'%}
{% block contenido %}
<div class="container my-5">
    <h1 class="display-6">Actualizar entrada de blog</h1>
</div>
<div class="container">
    <form class="bg-light border my-5 p-3 rounded shadow" method="post">
        {% csrf_token %}
        <div class="my-3">
            <div class="form-floating my-3">
                <input type="text" class="form-control" id="id_titulo" placeholder="x" name="titulo" value="{{entradablog.titulo}}" required>
                <label for="id_titulo">Título</label>
            </div>

            <div class="form-floating my-3">
                <textarea class="form-control" placeholder="x" id="id_descripcion" style="height:100px" name="contenido" required>{{entradablog.contenido}}</textarea>
                <label for="id_descripcion">Contenido</label>
            </div>
            
            <button type="submit" class="btn btn-primary" value="Update">Guardar</button>
        </div>
    </form>
</div>


{% endblock %}